apiVersion: v1
kind: ServiceAccount
metadata:
  name: observability-signal-ingestor
  namespace: zta-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: observability-signal-ingestor
rules:
  - apiGroups: ["zta.example.com"]
    resources: ["ztasignals","ztasignals/status"]
    verbs: ["get","list","watch","create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: observability-signal-ingestor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: observability-signal-ingestor
subjects:
  - kind: ServiceAccount
    name: observability-signal-ingestor
    namespace: zta-system
