apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-signal-generator
  namespace: zta-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aws-signal-generator
rules:
  - apiGroups: ["zta.example.com"]
    resources: ["ztasignals","ztasignals/status"]
    verbs: ["get","list","watch","create","patch","update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aws-signal-generator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aws-signal-generator
subjects:
  - kind: ServiceAccount
    name: aws-signal-generator
    namespace: zta-system
