apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: telemetry
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: "otel-collector"
        static_configs:
          - targets: ["otel-collector.telemetry.svc.cluster.local:8889"]

      - job_name: "kube-state-metrics"
        static_configs:
          - targets: ["kube-state-metrics.telemetry.svc.cluster.local:8080"]

      - job_name: "kyverno"
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: ["kyverno"]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
            action: keep
            regex: kyverno
          - source_labels: [__meta_kubernetes_pod_container_port_number]
            action: keep
            regex: "8000|9443|9090|9914"
