apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: zta-system
type: Opaque
stringData:
  # Optional for AWS telemetry/enforcement paths.
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: REPLACE_ME
  AWS_SECRET_ACCESS_KEY: REPLACE_ME
  # AWS_SESSION_TOKEN: REPLACE_ME_OPTIONAL
