apiVersion: v1
kind: Secret
metadata:
  name: pa-ssh-key
  namespace: zta-system
type: Opaque
stringData:
  # Paste the PRIVATE key content here (ed25519 recommended)
  # IMPORTANT: do NOT commit real private keys to git.
  id_ed25519: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    REPLACE_WITH_PRIVATE_KEY
    -----END OPENSSH PRIVATE KEY-----
